services:
  mongo:
    image: mongo:7.0
    container_name: quizduel-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --bind_ip_all

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quizduel-backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      # Use the MongoDB service hostname 'mongo'
      MONGODB_URI: mongodb://mongo:27017/your_db_name

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quizduel-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: quizduel-nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo-data:
